version: '2'

services:
  web:
    image: ${WEB_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webroot:/var/www/html:ro
