version: "3"

services:
  web:
    container_name: ${CONTAINER_NAME}
    labels:
      - traefik.enable=true
      ### Section HTTP
      - traefik.http.routers.http-get_bjphoster_com.entrypoints=http
      # redirect to HTTPS only
      - traefik.http.routers.http-get_bjphoster_com.middlewares=http-to-https
      - traefik.http.routers.http-get_bjphoster_com.rule=Host(`get.bjphoster.com`)
      ### Section HTTPS
      - traefik.http.routers.https-get_bjphoster_com.entrypoints=https
      # configure the exposed service
      - traefik.http.routers.https-get_bjphoster_com.rule=Host(`get.bjphoster.com`)
      # of course, enable TLS and it's certificate provider
      - traefik.http.routers.https-get_bjphoster_com.tls=true
      - traefik.http.routers.https-get_bjphoster_com.tls.certresolver=letsencrypt
    image: ${WEB_IMAGE}
    networks:
      - traefik-proxy
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webroot:/var/www/html:ro

networks:
  traefik-proxy:
    external: true
